Updated github workflow

diff --git a/.github/workflows/deploy-bts-website.yml b/.github/workflows/deploy-bts-website.yml
--- a/.github/workflows/deploy-bts-website.yml
+++ b/.github/workflows/deploy-bts-website.yml
@@ -1,15 +1,15 @@
 name: Deploy Bengali Text Summarizer
 
 on:
-  workflow_dispatch:  # Allows manual triggering of the workflow
+  push:
+    branches: ["main"]
+  workflow_dispatch:
 
-# Define the required permissions for GitHub Actions
 permissions:
   contents: read
   pages: write
   id-token: write
 
-# Ensure only one deployment workflow runs at a time
 concurrency:
   group: 'pages'
   cancel-in-progress: false
@@ -21,32 +21,63 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: '20'
-          cache: 'npm'  # Enables caching of npm dependencies
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+      - name: Setup Pages
+        uses: actions/configure-pages@v5
+        with:
+          static_site_generator: next
+
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            .next/cache
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
 
       - name: Install dependencies
-        run: npm ci
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
       - name: Build with Next.js
-        run: npm run build
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
         env:
-          # Set the base path for asset references in the build
           NEXT_PUBLIC_BASE_PATH: '/bengali-text-summarizer'
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./out  # Directory containing the built static files
+          path: ./out
 
   deploy:
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
-    needs: build  # Ensures the build job completes before deploying
+    needs: build
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
